# Generated by Django 2.2.17 on 2021-01-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('beginDate', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluateBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=5000)),
                ('copyright', models.CharField(max_length=200)),
                ('score', models.IntegerField()),
                ('beginDate', models.DateTimeField(editable=False)),
                ('deadline', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('donationGoal', models.IntegerField()),
            ],
        ),
    ]
