# Generated by Django 2.2.17 on 2021-01-17 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=5000)),
                ('copyright', models.CharField(max_length=200)),
                ('score', models.IntegerField()),
                ('beginDate', models.DateTimeField(editable=False)),
                ('deadline', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('donationGoal', models.IntegerField()),
                ('annoncer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annoncer', to=settings.AUTH_USER_MODEL)),
                ('donaters', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluateBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.Projects')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('beginDate', models.DateTimeField(editable=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.Projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
