version: "2"
services:
  app:
    entrypoint: /entrypoint.sh
    restart: always
    build: . # Current directory!
    command: "python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
