# Generated by Django 2.2.17 on 2021-01-21 16:53

from django.db import migrations, models
import mopga.modules.project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('beginDate', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluateBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectId', models.IntegerField()),
                ('path', models.ImageField(upload_to=mopga.modules.project.models.setImagePath)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=5000)),
                ('copyright', models.CharField(max_length=200)),
                ('beginDate', models.DateTimeField(editable=False)),
                ('deadline', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('donationGoal', models.IntegerField(default=0)),
                ('moneyCollected', models.IntegerField(default=0)),
                ('imageName', models.CharField(max_length=200)),
                ('note', models.FloatField(default=0.0)),
            ],
        ),
    ]
